development:
  adapter: mysql2
  database: muni_maps
  username: root
  password:
  host: localhost

production:
  adapter: postgresql
  database: muni_maps
  username: www-data
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

test:
  adapter: mysql2
  database: muni_maps_test
  username: root
  password:
  host: localhost